---
#management.server.address: 127.0.0.1
#management.endpoint.shutdown.enabled: true
management.endpoints.web.exposure.include: loggers,health,readiness

server: #org.springframework.boot.autoconfigure.web.ServerProperties , gateway使用的是 NettyReactiveWebServerFactory来创建WebServer
  port: 8080
  shutdown: graceful
  netty: 
  #为了使网关不会出现大量的TIME_WAIT（主动关闭方出现）且不会有大量的空闲连接，需要配置合理的maxKeepAliveRequests、keepAliveTimeout。不区分api还是openapi。
  #对maxKeepAliveRequests建议并发低的场景给几十-几百，高的场景数千，一般往较大数值考虑避免高并发时频繁关闭连接。如果前置有类似nginx则不配，信任它。
  #对idle-timeout建议并发低的场景60s，高的场景10s，避免空闲连接长时间占用。如果前置有类似nginx则配置600s。
  #网关这样的接入层需要考虑攻击防御，见DDoS防御 https://help.aliyun.com/document_detail/28401.html?spm=a2c4g.65932.0.0.69f46c81FR8AeE
    connection-timeout: 1000 # 客户端连接超时时间，默认无
#    maxKeepAliveRequests:  #长连接最多请求几次则关闭，默认无限。如果配置则必须>0，设置1就相当于禁用KeepAlive成为短连接，这时主动关闭方是服务端，会有大量的TIME_WAIT。
#    idle-timeout:  # 相当于nginx/tomcat的keepAliveTimeout，客户端长连接超时会被自动关闭。默认无限，由客户端关闭。

spring:
  lifecycle.timeout-per-shutdown-phase: 20s
  application:
    name: nursery-gateway
  cloud:
    loadbalancer: #LoadBalancerClientsProperties
      retry:
        enabled: false #默认true    
    gateway:   #https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/appendix.html
      discovery.locator.enabled: true #默认false，与服务发现集成，例如nacos
      httpclient:    #对下游服务的配置 org.springframework.cloud.gateway.config.HttpClientProperties
        connect-timeout: 1000    #The connect timeout in millis, the default is 45s.
        response-timeout: 5000    #The response timeout.
        pool.type: FIXED    #ELASTIC,FIXED,DISABLED.  Type of pool for HttpClient to use, defaults to ELASTIC.
        pool.acquire-timeout: 1000  #Only for type FIXED, the maximum time in millis to wait for acquiring.
        pool.eviction-interval: 0   #默认0.定时检查和回收连接池中不健康的连接的时间间隔，默认=0是不会生效；netty 连接池中的连接只有在取和放的时候才会根据max-idle-time判断连接是否需要释放 Perform regular eviction checks in the background at a specified interval. Disabled by default ({@link Duration#ZERO})
        pool.max-connections: 500    #Only for type FIXED, the maximum number of connections before starting pending acquisition on existing ones.
        pool.max-idle-time: 60000   #Time in millis after which the channel will be closed. If NULL, there is no max idle time.
        pool.max-life-time: 600000  #Duration after which the channel will be closed. If NULL, there is no max life time.
#        pool.metrics: false   #默认false.Enables channel pools metrics to be collected and registered in Micrometer. Disabled by default.
#        pool.name: proxy   #The channel pool map name, defaults to proxy.
#        proxy.host:   #Hostname for proxy configuration of Netty HttpClient.
#        proxy.non-proxy-hosts-pattern:    #Regular expression (Java) for a configured list of hosts. that should be reached directly, bypassing the proxy
#        proxy.username:    #Username for proxy configuration of Netty HttpClient.
#        proxy.password:    #Password for proxy configuration of Netty HttpClient.
#        proxy.port:    #Port for proxy configuration of Netty HttpClient.
#        proxy.type:    #proxyType for proxy configuration of Netty HttpClient.
#        max-header-size:   #The max response header size.
  codec:
    max-in-memory-size: 262144 #与能够接受的请求体大小有关，不足会报错，默认262144字节     



